# Helper to create a user + employee + personal detail together
def create_user_and_employee(email:, role:, department:, position_title:, hire_date:, leave_balance:)
  user = User.create!(
    email: email,
    password: "password",
    role: role
  )

  employee = Hr::Employee.create!(
    user: user,
    department: department,
    position_title: position_title,
    hire_date: hire_date,
    status: :active,
    leave_balance: leave_balance
    # hamzis_id auto-generated by callback
  )

  Hr::PersonalDetail.create!(
    employee: employee,
    first_name: email.split("@").first.capitalize,
    last_name: "Test",
    dob: Date.new(1990, 1, 1),
    gender: :male,
    bank_name: "Test Bank",
    account_number: "1234567890",
    account_name: "#{email.split('@').first.capitalize} Test",
    means_of_identification: :nin,
    id_number: SecureRandom.hex(6),
    marital_status: :single,
    address: "123 Example Street",
    phone_number: "08012345678"
  )

  employee
end

# --- Employees ---
ceo = create_user_and_employee(
  email: "ceo@example.com",
  role: :ceo,
  department: "Executive",
  position_title: "Chief Executive Officer",
  hire_date: Date.new(2020, 1, 1),
  leave_balance: 30
)

cto = create_user_and_employee(
  email: "cto@example.com",
  role: :cto,
  department: "Technical",
  position_title: "Chief Technical Officer",
  hire_date: Date.new(2021, 1, 1),
  leave_balance: 25
)

qs = create_user_and_employee(
  email: "qs@example.com",
  role: :qs,
  department: "Quality",
  position_title: "Quantity Surveyor",
  hire_date: Date.new(2022, 1, 1),
  leave_balance: 20
)

site_manager = create_user_and_employee(
  email: "site_manager@example.com",
  role: :site_manager,
  department: "Operations",
  position_title: "Site Manager",
  hire_date: Date.new(2021, 6, 1),
  leave_balance: 18
)

engineer = create_user_and_employee(
  email: "engineer@example.com",
  role: :engineer,
  department: "Engineering",
  position_title: "Engineer",
  hire_date: Date.new(2022, 3, 1),
  leave_balance: 15
)

storekeeper = create_user_and_employee(
  email: "storekeeper@example.com",
  role: :storekeeper,
  department: "Inventory",
  position_title: "Storekeeper",
  hire_date: Date.new(2023, 1, 1),
  leave_balance: 12
)

hr = create_user_and_employee(
  email: "hr@example.com",
  role: :hr,
  department: "Human Resources",
  position_title: "HR Officer",
  hire_date: Date.new(2022, 9, 1),
  leave_balance: 20
)

accountant = create_user_and_employee(
  email: "accountant@example.com",
  role: :accountant,
  department: "Finance",
  position_title: "Accountant",
  hire_date: Date.new(2021, 11, 1),
  leave_balance: 22
)

admin = create_user_and_employee(
  email: "admin@example.com",
  role: :admin,
  department: "Administration",
  position_title: "System Administrator",
  hire_date: Date.new(2020, 5, 1),
  leave_balance: 25
)

# --- Hierarchy ---
cto.update!(manager: ceo)
qs.update!(manager: cto)
site_manager.update!(manager: qs)
engineer.update!(manager: site_manager)
storekeeper.update!(manager: engineer)

hr.update!(manager: ceo)          # HR reports directly to CEO
accountant.update!(manager: hr)   # Accountant reports to HR
admin.update!(manager: ceo)       # Admin reports directly to CEO

# --- Clients ---
client1_user = User.create!(
  email: "client1@example.com",
  password: "password",
  role: :client
)

client2_user = User.create!(
  email: "client2@example.com",
  password: "password",
  role: :client
)

Business::Client.create!(
  user: client1_user,
  name: "Client One Ltd.",
  email: "client1@example.com"
)

Business::Client.create!(
  user: client2_user,
  name: "Client Two Ltd.",
  email: "client2@example.com"
)

puts "Seeded employees with personal details, hierarchy, and clients."
